# Generated by Django 3.1.3 on 2020-11-30 00:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.Field(choices=[('NW', 'New'), ('IP', 'In Progress'), ('DN', 'Done'), ('IV', 'Invalid')])),
                ('date_filled', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_ass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ass', to=settings.AUTH_USER_MODEL)),
                ('user_complete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_complete', to=settings.AUTH_USER_MODEL)),
                ('user_fill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_fill', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
