# Generated by Django 3.1.3 on 2020-11-30 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0003_custuser_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickets',
            name='status',
        ),
    ]
