# Generated by Django 3.1.3 on 2020-11-30 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0004_remove_tickets_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickets',
            old_name='date_filled',
            new_name='date_filed',
        ),
        migrations.RenameField(
            model_name='tickets',
            old_name='user_ass',
            new_name='user_assign',
        ),
        migrations.RenameField(
            model_name='tickets',
            old_name='user_fill',
            new_name='user_filed',
        ),
    ]
